@startuml


interface Многоугольник
interface Пятиугольник
class ПятиугольникImpl

interface Шестиугольник
class ШестиугольникImpl

interface Семиугольник
class СемиугольникImpl

interface Восьмиугольник
class ВосьмиугольникImpl

interface Девятиугольник
class ДевятиугольникImpl

interface Десятиугольник
class ДесятиугольникImpl

Форма <-- Многоугольник

Многоугольник <.. Пятиугольник
Многоугольник <.. Шестиугольник
Многоугольник <.. Семиугольник
Многоугольник <.. Восьмиугольник
Многоугольник <.. Девятиугольник
Многоугольник <.. Десятиугольник

Пятиугольник  <-- ПятиугольникImpl
Шестиугольник  <-- ШестиугольникImpl
Семиугольник  <-- СемиугольникImpl
Восьмиугольник  <-- ВосьмиугольникImpl
Девятиугольник  <-- ДевятиугольникImpl
Десятиугольник  <-- ДесятиугольникImpl

Правильный <... Пятиугольник
Правильный <... Шестиугольник
Правильный <... Восьмиугольник
Правильный <... Десятиугольник


@enduml