@startuml

interface Форма
interface Равнобедренный
interface Прямоугольный
interface Правильный
interface Равносторонний
interface Разносторонний
interface Параллелограмм
interface Четырехугольник
class ПараллелограммImpl
interface Прямоугольник
class ПрямоугольникImpl
interface Ромб
class РомбImpl
class КвадратImpl
interface Трапеция
class ТрапецияImpl

'ветка четырехугольников
Форма <-- Четырехугольник
Четырехугольник <-- Параллелограмм
Параллелограмм <-- ПараллелограммImpl
Параллелограмм <-- Прямоугольник
Прямоугольник <-- ПрямоугольникImpl
Параллелограмм <-- Ромб
Ромб <-- РомбImpl
Прямоугольник <-- КвадратImpl
Ромб <-- КвадратImpl
Четырехугольник <-- Трапеция
Трапеция <-- ТрапецияImpl

Правильный <... Четырехугольник
Равносторонний <..Четырехугольник
Разносторонний <..Четырехугольник

Равнобедренный <.... Трапеция
Прямоугольный <.... Трапеция
@enduml