@startuml
'https://plantuml.com/class-diagram

interface Правильный
interface Равносторонний
interface Разносторонний
interface Равнобедренный
interface Прямоугольный
interface Остроугольный
interface Тупоугольный

interface Форма
interface ОбщийМногоугольник
interface Эллипс
class Круг
class Овал

interface Треугольник
class ТреугольникImpl



interface Четырехугольник
interface Параллелограмм
class ПараллелограммImpl

interface Прямоугольник
class ПрямоугольникImpl

interface Ромб
class РомбImpl

class КвадратImpl

interface Трапеция
class ТрапецияImpl



interface Пятиугольник
class ПятиугольникImpl

interface Шестиугольник
class ШестиугольникImpl

interface Семиугольник
class СемиугольникImpl

interface Восьмиугольник
class ВосьмиугольникImpl

interface Девятиугольник
class ДевятиугольникImpl

interface Десятиугольник
class ДесятиугольникImpl


Правильный <... Треугольник
Равносторонний <... Треугольник
Разносторонний <... Треугольник
Равнобедренный <... Треугольник
Прямоугольный <... Треугольник
Остроугольный <... Треугольник
Тупоугольный <... Треугольник

Правильный <... Четырехугольник
Равносторонний <..Четырехугольник
Разносторонний <..Четырехугольник

'Правильный <.. Четырехугольник
'Правильный <.. Пятиугольник
'Правильный <.. Шестиугольник
'Правильный <.. Восьмиугольник
'Правильный <.. Десятиугольник

Форма <--- ОбщийМногоугольник

'ветка элипсов
Форма <-- Эллипс
Эллипс <-- Круг
Эллипс <-- Овал

'ветка треугольников
ОбщийМногоугольник <.. Треугольник
Треугольник <-- ТреугольникImpl


'ветка четырехугольников
ОбщийМногоугольник <.. Четырехугольник
Четырехугольник <-- Параллелограмм
Параллелограмм <-- ПараллелограммImpl
Параллелограмм <-- Прямоугольник
Прямоугольник <-- ПрямоугольникImpl
Параллелограмм <-- Ромб
Ромб <-- РомбImpl
Прямоугольник <-- КвадратImpl
Ромб <-- КвадратImpl
Четырехугольник <-- Трапеция
Трапеция <-- ТрапецияImpl



Равнобедренный <.... Трапеция
Прямоугольный <.... Трапеция



ОбщийМногоугольник <.. Пятиугольник
ОбщийМногоугольник <.. Шестиугольник
ОбщийМногоугольник <.. Семиугольник
ОбщийМногоугольник <.. Восьмиугольник
ОбщийМногоугольник <.. Девятиугольник
ОбщийМногоугольник <.. Десятиугольник



Пятиугольник  <-- ПятиугольникImpl
Шестиугольник  <-- ШестиугольникImpl
Семиугольник  <-- СемиугольникImpl
Восьмиугольник  <-- ВосьмиугольникImpl
Девятиугольник  <-- ДевятиугольникImpl
Десятиугольник  <-- ДесятиугольникImpl
@enduml