@startuml

interface Форма
interface Правильный
interface Равносторонний
interface Разносторонний
interface Равнобедренный
interface Прямоугольный
interface Остроугольный
interface Тупоугольный

interface Треугольник
class ТреугольникImpl

'ветка треугольников
Форма <-- Треугольник
Треугольник <-- ТреугольникImpl
Правильный <... Треугольник
Равносторонний <... Треугольник
Разносторонний <... Треугольник
Равнобедренный <... Треугольник
Прямоугольный <... Треугольник
Остроугольный <... Треугольник
Тупоугольный <... Треугольник

@enduml